# Generated by Django 5.1.1 on 2024-10-07 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadocivil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_expediente', models.CharField(max_length=50)),
                ('n_ingreso', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('profesion_ocupacion', models.CharField(max_length=100)),
                ('albergue', models.BooleanField(default=False)),
                ('enfermedad', models.BooleanField(default=False)),
                ('vivienda', models.BooleanField(default=False)),
                ('dependencias', models.BooleanField(default=False)),
                ('gestacion', models.BooleanField(default=False)),
                ('descripcion_hecho', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.area')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.departamento')),
                ('estadocivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estadocivil')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.municipio')),
            ],
        ),
    ]
