# Generated by Django 5.1.1 on 2024-10-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_violencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='participante',
            name='area',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='estadocivil',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='municipio',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='EstadoCivil',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
