# Generated by Django 5.1.1 on 2024-10-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciaAdictiva',
            fields=[
                ('id_dependencia', models.AutoField(primary_key=True, serialize=False)),
                ('dependencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id_escolaridad', models.AutoField(primary_key=True, serialize=False)),
                ('escolaridad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVivienda',
            fields=[
                ('id_estado_vivienda', models.AutoField(primary_key=True, serialize=False)),
                ('estado_vivienda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id_etnia', models.AutoField(primary_key=True, serialize=False)),
                ('etnia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionAfinidad',
            fields=[
                ('id_relacionafinidad', models.AutoField(primary_key=True, serialize=False)),
                ('relacion_afinidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id_religion', models.AutoField(primary_key=True, serialize=False)),
                ('religion', models.CharField(max_length=50)),
            ],
        ),
    ]
