# Generated by Django 5.1.1 on 2024-10-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_bienes_tipoantecedente_participante_hijo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='apoyo_familiar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='enfermedad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='referente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tiempo_gestacion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
