# Generated by Django 5.1.1 on 2024-10-12 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alter_participante_apoyo_familiar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='antecedentes_enfermedad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='apoyo_familiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.dependenciaadictiva'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='dependencia_adictiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='estado_gestacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='lectura_escritura',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participante',
            name='presenta_discapacidad',
            field=models.BooleanField(default=False),
        ),
    ]
