# Generated by Django 5.1.1 on 2024-10-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_alter_hecho_tipo_violencia_alter_participante_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijo',
            name='establecimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
