# Generated by Django 5.1.1 on 2024-10-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_alter_hijo_establecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho',
            name='fecha_denuncia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='institucion_denuncia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
