# Generated by Django 5.1.1 on 2024-10-14 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_alter_hecho_fecha_denuncia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agresor',
            name='actividad_laboral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.bienes'),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.dependenciaadictiva'),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='descripcion_armas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='descripcion_enfermedad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='ingreso_mensual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='nombre_lugar_trabajo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='otras_dependencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='otros_antecedentes_conflic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='otros_bienes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='referencias_personales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agresor',
            name='tipo_antecedente_conflic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.tipoantecedente'),
        ),
    ]
