# Generated by Django 5.1.1 on 2024-10-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_alter_agresor_actividad_laboral_alter_agresor_bien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDeAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_atencion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('actividad', models.TextField()),
                ('resultados', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('area_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.areadeatencion')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.municipio')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.participante')),
            ],
        ),
    ]
