# Generated by Django 5.1.1 on 2024-10-15 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_areadeatencion_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albergue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('cantidad_hijos', models.IntegerField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.participante')),
            ],
        ),
    ]
