# Generated by Django 5.1.1 on 2024-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_areadeatencion_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agresor',
            name='dpi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='dpi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
