# Generated by Django 5.1.1 on 2024-10-15 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_albergue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albergue',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='albergue',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
