# Generated by Django 5.1.1 on 2024-10-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_alter_agresor_dpi_alter_participante_dpi'),
        ('sistema', '0015_alter_albergue_fecha_ingreso_and_more'),
    ]

    operations = [
    ]
